echo "==========================Lock map==========================="
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 1 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 2 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 3 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 4 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.1 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.2 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.3 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.4 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.1 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.2 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.3 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.4 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.1 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.2 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.3 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.4 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 8 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 9 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 10 lock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 11 lock

echo "===========================RWLock map==========================="
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 1 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 2 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 3 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 4 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.1 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.2 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.3 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.4 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.1 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.2 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.3 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.4 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.1 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.2 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.3 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.4 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 8 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 9 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 10 rwlock
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 11 rwlock

echo "===========================Parallel map==========================="
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 1 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 2 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 3 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 4 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.1 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.2 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.3 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.4 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.1 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.2 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.3 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.4 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.1 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.2 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.3 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.4 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 8 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 9 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 10 parallel
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 11 parallel

echo "===========================gotomic map==========================="
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 1 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 2 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 3 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 4 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.1 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.2 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.3 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.4 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.1 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.2 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.3 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.4 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.1 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.2 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.3 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.4 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 8 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 9 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 10 gotomic
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 11 gotomic

echo "===========================Chinese map==========================="
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 1 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 2 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 3 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 4 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.1 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.2 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.3 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 5.4 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.1 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.2 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.3 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 6.4 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.1 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.2 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.3 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 7.4 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 8 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 9 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 10 chinese
perf stat -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./app 11 chinese
